cw1_8567_view/Models/ErrorViewModel.cs
using System;

namespace cw1_8567_view.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

cw1_8567_view/Models/Room.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cw1_8567_view.Models
{
    public class Room
    {
        public int? RoomId { get; set; }
        public int RoomNumber { get; set; }
        public int Floor { get; set; }
        public bool IsAvailable { get; set; }
        public decimal Price { get; set; }
        public string Brief { get; set; }
    }
}

cw1_8567_view/Controllers/HomeController.cs
using cw1_8567_view.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace cw1_8567_view.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

cw1_8567_view/Controllers/RoomsController.cs
using cw1_8567_view.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cw1_8567_view.Controllers
{
    public class RoomsController : Controller
    {
        // GET: RoomsContrller
        public async Task<ActionResult> Index()
        {
            var service = new Services.RoomService();
            return View(await service.FindAll());
        }

        // GET: RoomsContrller/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var service = new Services.RoomService();
            return View(await service.FindOne(id));
        }

        // GET: RoomsContrller/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RoomsContrller/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Room collection)
        {
            try
            {
                var service = new Services.RoomService();
                service.Create(collection);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                throw e;
                return View();
            }
        }

        // GET: RoomsContrller/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var service = new Services.RoomService();
            return View(await service.FindOne(id));
        }

        // POST: RoomsContrller/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Room collection)
        {
            try
            {
                collection.RoomId = id;
                var service = new Services.RoomService();
                service.Update(collection, id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RoomsContrller/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            return View();
        }

        // POST: RoomsContrller/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, Room collection)
        {
            try
            {
                var service = new Services.RoomService();
                service.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

cw1_8567_view/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

cw1_8567_view/Views/Rooms/Create.cshtml
@model cw1_8567_view.Models.Room

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="RoomNumber" class="control-label"></label>
                <input asp-for="RoomNumber" class="form-control" />
                <span asp-validation-for="RoomNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Floor" class="control-label"></label>
                <input asp-for="Floor" class="form-control" />
                <span asp-validation-for="Floor" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brief" class="control-label"></label>
                <input asp-for="Brief" class="form-control" />
                <span asp-validation-for="Brief" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

cw1_8567_view/Views/Rooms/Delete.cshtml
@model cw1_8567_view.Models.Room

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Floor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Floor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brief)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brief)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

cw1_8567_view/Views/Rooms/Details.cshtml
@model cw1_8567_view.Models.Room

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Floor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Floor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brief)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brief)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

cw1_8567_view/Views/Rooms/Edit.cshtml
@model cw1_8567_view.Models.Room

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                <input asp-for="RoomId" class="form-control" />
                <span asp-validation-for="RoomId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomNumber" class="control-label"></label>
                <input asp-for="RoomNumber" class="form-control" />
                <span asp-validation-for="RoomNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Floor" class="control-label"></label>
                <input asp-for="Floor" class="form-control" />
                <span asp-validation-for="Floor" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brief" class="control-label"></label>
                <input asp-for="Brief" class="form-control" />
                <span asp-validation-for="Brief" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

cw1_8567_view/Views/Rooms/Index.cshtml
@model IEnumerable<cw1_8567_view.Models.Room>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RoomId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RoomNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Floor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAvailable)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Brief)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RoomId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoomNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Floor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAvailable)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brief)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.RoomId }) |
                @Html.ActionLink("Details", "Details", new {  id=item.RoomId }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.RoomId })
            </td>
        </tr>
}
    </tbody>
</table>

cw1_8567_view/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cw1_8567_view</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">cw1_8567_view</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - cw1_8567_view - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>